// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppxkfcuehldqlwkfootm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBweGtmY3VlaGxkcWx3a2Zvb3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NTc2MjQsImV4cCI6MjA3NDQzMzYyNH0.iE15Zm-txQEVIKgoZSQNf6su_aKBLRSyQAr3CuL63Bk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});